### ISSUE TITLE
How can I change cancel button text?

### ISSUE THREAD

**Issue by ismaiI1** [fccaikai/BottomMenuTutorial#2]
How can I change cancel button text?

**Comment by caikaidev** [comment]
you can define` <string name="cancel">your cancel text</string>` in strings.xml

**Comment by caikaidev** [comment]
Hi,You can update 1.0.2 version. And , use `BottomDialog.newInstance("titleText","cancelText",new String[]{"item1","item2"});` to set cancel button text. see [MainFragment.java](https://github.com/fccaikai/BottomMenuTutorial/blob/master/app/src/main/java/com/kcode/bottommenututorial/MainFragment.java)

**Comment by ismaiI1** [comment]
Thanks..
