### ISSUE TITLE
点击空白地方有问题

### ISSUE THREAD

**Issue by FlogFly** [fccaikai/BottomMenuTutorial#3]
跳出弹框后，你点击框外的空白的地方，本来点一下是弹框消失，然后你不停的点击空白地方。然后你就看到弹框不停的在那里跳动。。。可以试试。

**Comment by caikaidev** [comment]
谢谢反馈，已修复。请升级到最新1.0.3版本。
问题是由于不停点击空白区域，一直在响应点击事件，导致消失动画重复执行引起。
