### ISSUE TITLE
又来提问题了。onTouch处的优化

### ISSUE THREAD

**Issue by FlogFly** [fccaikai/BottomMenuTutorial#5]
window.getDecorView().setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                dismiss();
                return true;
            }
        });

这么写有问题的。因为是onTouch就去执行，所以如果你在里面打上Log，你就会发现多次执行dismiss方法，虽然对于使用上是没有问题，但是最好做修改，因为不然你摸其他地方，其本上都是执行好几次。可以在手指收起来的时候去执行，这样只会执行一次

window.getDecorView().setOnTouchListener(new View.OnTouchListener() {
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_UP) {               
                    BottomDialog.this.dismiss();
                    return true;
                }
                return false;
            }
        });

**Comment by caikaidev** [comment]
感谢建议，已经优化了，确实只要处理一次就好了。

**Comment by FlogFly** [comment]
hi,我这里有个地方写错了。不能是up时候return true, 其他return false ,要都return true，不然刚碰到的时候，因为DialogFragment有点击外面会有消失的事件，就会让Dialog消失，从而不走我们的动画那段消失代码。

**Comment by caikaidev** [comment]
是都出return true的。
